apiVersion: grizzly.grafana.com/v1alpha1
kind: AlertRuleGroup
metadata:
    name: ae1un1b4e6i9sd.1m
spec:
    folderUid: ae1un1b4e6i9sd
    interval: 60
    rules:
        - annotations:
            __dashboardUid__: ce19yxmtnfx1cd
            __panelId__: "4"
          condition: B
          data:
            - datasourceUid: de19y31uykhkwf
              model:
                editorMode: builder
                expr: sum(rate({tag="package-to-upgrade"} [$__auto]))
                intervalMs: 1000
                maxDataPoints: 43200
                queryType: range
                refId: A
              queryType: range
              refId: A
              relativeTimeRange:
                from: 900
            - datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: sum
                refId: B
                type: reduce
              refId: B
              relativeTimeRange:
                from: 900
          execErrState: Error
          folderUID: ae1un1b4e6i9sd
          for: 0s
          id: 1
          noDataState: NoData
          notification_settings:
            group_by: null
            mute_time_intervals: null
            receiver: ntfy
          orgID: 1
          ruleGroup: 1m
          title: Security packages to upgrade
          uid: ce1tuk9726i9sa
          updated: "2024-10-24T16:57:37.000Z"
    title: 1m
