Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox"

  # Configure read ip, more info see https://github.com/BerlinVagrant/vagrant-dns/blob/e074ada87dedb6e14e9db7f9b92cf4e72cba16ac/README.md?plain=1#L207
  config.dns.ip = -> (vm, opts) do
    ip = nil
    vm.communicate.execute("hostname -I | cut -d ' ' -f 2") do |type, data|
      ip = data.strip if type == :stdout
    end
    ip
  end

  config.vm.define "server1" do |server|
    server.vm.box = "bento/ubuntu-24.04" # 24.04 LTS
    server.vm.hostname = "server1"
    server.dns.tld = "test"
    server.dns.patterns = ["server1.vagrant.test"]
    server.vm.network "private_network", type: "dhcp"
    server.vm.synced_folder '.', '/vagrant/', disabled: false

    server.vm.provider :virtualbox do |vb|
      vb.memory = '2096'
      vb.cpus = '1'
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end
  end

  config.vm.define "server2" do |server|
    server.vm.box = "bento/ubuntu-24.04" # 24.04 LTS
    server.vm.hostname = "server2"
    server.dns.tld = "test"
    server.dns.patterns = ["server2.vagrant.test", "grafana.vagrant.test", "loki.vagrant.test"]
    server.vm.network "private_network", type: "dhcp"
    server.vm.synced_folder '.', '/vagrant/', disabled: false

    server.vm.provider :virtualbox do |vb|
      vb.memory = '2096'
      vb.cpus = '1'
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end
  end
end
